// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-tasks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/tool-runtime.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
var readRuntimeEnv = (name) => {
  if (typeof Deno !== "undefined") return Deno.env.get(name) ?? void 0;
  if (typeof process !== "undefined") return process.env[name];
  return void 0;
};
var safeJson = (value) => {
  try {
    return JSON.stringify(value, null, 2);
  } catch (error) {
    return `[unserializable: ${error instanceof Error ? error.message : String(error)}]`;
  }
};
var errorMessage = (error) => {
  if (error instanceof Error) return error.message;
  if (typeof error === "object" && error && "message" in error) return String(error.message);
  return String(error);
};
var errorStack = (error) => error instanceof Error ? error.stack : void 0;
var getSupabaseConfig = () => {
  const supabaseUrl = readRuntimeEnv("SUPABASE_URL") ?? "https://tbigtlfuittunagpyoxk.supabase.co";
  const supabaseKey = readRuntimeEnv("SUPABASE_PUBLISHABLE_KEY") ?? readRuntimeEnv("SUPABASE_ANON_KEY") ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiaWd0bGZ1aXR0dW5hZ3B5b3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2ODM4MzcsImV4cCI6MjA4NjI1OTgzN30.9ZZfx3MjsudvnX4-mnFj4OIiQj-BQ-TuptTQB7r6iW8";
  return { supabaseUrl, supabaseKey };
};
var createUserClient = (ctx) => {
  const { supabaseUrl, supabaseKey } = getSupabaseConfig();
  if (!supabaseUrl || !supabaseKey) {
    throw new Error("MCP backend configuration is missing the database URL or publishable key.");
  }
  return createClient(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
};
async function runTool(toolName, input, ctx, handler) {
  const startedAt = Date.now();
  try {
    console.log(`[MCP:${toolName}] request.received`, {
      input: safeJson(input),
      hasToken: Boolean(ctx.getToken()),
      tokenLength: ctx.getToken()?.length ?? 0,
      userId: ctx.getUserId(),
      userEmail: ctx.getUserEmail(),
      clientId: ctx.getClientId(),
      scopes: ctx.getScopes()
    });
    if (!ctx.isAuthenticated() || !ctx.getToken() || !ctx.getUserId()) {
      console.warn(`[MCP:${toolName}] auth.failed`, { authenticated: ctx.isAuthenticated(), userId: ctx.getUserId() });
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = createUserClient(ctx);
    const { data: userData, error: userError } = await client.auth.getUser(ctx.getToken());
    if (userError || !userData.user) {
      console.error(`[MCP:${toolName}] auth.getUser.failed`, {
        message: userError?.message,
        userId: ctx.getUserId(),
        userEmail: ctx.getUserEmail()
      });
      return { content: [{ type: "text", text: userError?.message ?? "Could not resolve authenticated user" }], isError: true };
    }
    const runtime = {
      ctx,
      userId: ctx.getUserId(),
      userEmail: userData.user.email ?? ctx.getUserEmail(),
      client,
      logDbResult: (operation, result2) => {
        console.log(`[MCP:${toolName}] db.${operation}`, {
          hasError: Boolean(result2.error),
          error: result2.error ? errorMessage(result2.error) : void 0,
          data: result2.error ? void 0 : safeJson(result2.data)
        });
      },
      ok: (label, data, structuredContent) => {
        const content = [{ type: "text", text: `${label}:
${safeJson(data)}` }];
        const response = { content, structuredContent };
        console.log(`[MCP:${toolName}] response.ok`, { durationMs: Date.now() - startedAt, label });
        return response;
      },
      fail: (message, details) => {
        console.error(`[MCP:${toolName}] response.error`, { durationMs: Date.now() - startedAt, message, details });
        return { content: [{ type: "text", text: message }], isError: true };
      }
    };
    console.log(`[MCP:${toolName}] auth.ok`, { userId: runtime.userId, userEmail: runtime.userEmail });
    const result = await handler(input, runtime);
    console.log(`[MCP:${toolName}] response.returned`, { durationMs: Date.now() - startedAt, isError: Boolean(result.isError) });
    return result;
  } catch (error) {
    console.error(`[MCP:${toolName}] exception`, {
      durationMs: Date.now() - startedAt,
      message: errorMessage(error),
      stack: errorStack(error)
    });
    return { content: [{ type: "text", text: errorMessage(error) }], isError: true };
  }
}

// src/lib/mcp/tools/list-my-tasks.ts
var list_my_tasks_default = defineTool({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List tasks belonging to the signed-in user. Optional filters by date (YYYY-MM-DD) or status.",
  inputSchema: {
    date: z.string().optional().describe("Filter by date (YYYY-MM-DD)"),
    status: z.enum(["Not Started", "In Progress", "Finished"]).optional(),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => runTool("list_my_tasks", input, ctx, async ({ date, status, limit }, runtime) => {
    let q = runtime.client.from("tasks").select("*").eq("user_id", runtime.userId).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (date) q = q.eq("date", date);
    if (status) q = q.eq("status", status);
    const result = await q;
    runtime.logDbResult("list_my_tasks.select", result);
    if (result.error) {
      return runtime.fail(result.error.message);
    }
    return runtime.ok("Tasks", result.data ?? [], { tasks: result.data ?? [] });
  })
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a task for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1),
    description: z2.string().optional(),
    category: z2.string().optional().describe("Task category e.g. Development, Design, Video, Ads"),
    date: z2.string().describe("Date in YYYY-MM-DD"),
    target_minutes: z2.number().int().positive().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => runTool("create_task", input, ctx, async (args, runtime) => {
    const result = await runtime.client.from("tasks").insert({
      user_id: runtime.userId,
      title: args.title,
      description: args.description ?? null,
      category: args.category ?? "Development",
      date: args.date,
      target_minutes: args.target_minutes ?? null,
      status: "Not Started"
    }).select().single();
    runtime.logDbResult("create_task.insert", result);
    if (result.error) {
      return runtime.fail(result.error.message);
    }
    return runtime.ok("Created task", result.data, { task: result.data });
  })
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as Finished, stop any open timer, and optionally attach completion notes and a project link.",
  inputSchema: {
    task_id: z3.string().uuid(),
    completion_notes: z3.string().optional(),
    project_link: z3.string().url().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => runTool("complete_task", input, ctx, async ({ task_id, completion_notes, project_link }, runtime) => {
    const stopResult = await runtime.client.from("time_sessions").update({ end_time: Date.now() }).eq("task_id", task_id).eq("created_by", runtime.userId).is("end_time", null).select();
    runtime.logDbResult("complete_task.stop_open_sessions", stopResult);
    if (stopResult.error) return runtime.fail(stopResult.error.message);
    const updates = { status: "Finished" };
    if (completion_notes) updates.completion_notes = completion_notes;
    if (project_link) updates.project_link = project_link;
    const result = await runtime.client.from("tasks").update(updates).eq("id", task_id).eq("user_id", runtime.userId).select().single();
    runtime.logDbResult("complete_task.update", result);
    if (result.error) {
      return runtime.fail(result.error.message);
    }
    return runtime.ok("Completed task", result.data, { task: result.data, stopped_sessions: stopResult.data ?? [] });
  })
});

// src/lib/mcp/tools/start-timer.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var start_timer_default = defineTool4({
  name: "start_timer",
  title: "Start timer",
  description: "Start a time session on one of the signed-in user's tasks and set it to In Progress.",
  inputSchema: { task_id: z4.string().uuid() },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (input, ctx) => runTool("start_timer", input, ctx, async ({ task_id }, runtime) => {
    const closeOtherSessions = await runtime.client.from("time_sessions").update({ end_time: Date.now() }).eq("created_by", runtime.userId).is("end_time", null).select();
    runtime.logDbResult("start_timer.close_existing", closeOtherSessions);
    if (closeOtherSessions.error) return runtime.fail(closeOtherSessions.error.message);
    const result = await runtime.client.from("time_sessions").insert({ task_id, start_time: Date.now(), created_by: runtime.userId }).select().single();
    runtime.logDbResult("start_timer.insert", result);
    if (result.error) {
      return runtime.fail(result.error.message);
    }
    const updateResult = await runtime.client.from("tasks").update({ status: "In Progress" }).eq("id", task_id).eq("user_id", runtime.userId).select().single();
    runtime.logDbResult("start_timer.update_task", updateResult);
    if (updateResult.error) return runtime.fail(updateResult.error.message);
    return runtime.ok("Started timer", result.data, { session: result.data, task: updateResult.data });
  })
});

// src/lib/mcp/tools/stop-timer.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var stop_timer_default = defineTool5({
  name: "stop_timer",
  title: "Stop timer",
  description: "Stop the currently open time session on the signed-in user's task.",
  inputSchema: { task_id: z5.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => runTool("stop_timer", input, ctx, async ({ task_id }, runtime) => {
    const result = await runtime.client.from("time_sessions").update({ end_time: Date.now() }).eq("task_id", task_id).eq("created_by", runtime.userId).is("end_time", null).select();
    runtime.logDbResult("stop_timer.update", result);
    if (result.error) {
      return runtime.fail(result.error.message);
    }
    return runtime.ok("Stopped timer", result.data ?? [], { sessions: result.data ?? [] });
  })
});

// src/lib/mcp/tools/team-activity.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
var team_activity_default = defineTool6({
  name: "team_activity",
  title: "Team activity snapshot",
  description: "Get the current team activity snapshot (admin only). Returns each member's active task and today's todo/progress/completed lists.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => runTool("team_activity", input, ctx, async (_, runtime) => {
    const result = await runtime.client.rpc("get_team_activity");
    runtime.logDbResult("team_activity.rpc", result);
    if (result.error) {
      return runtime.fail(result.error.message);
    }
    return runtime.ok("Team activity", result.data ?? [], { activity: result.data ?? [] });
  })
});

// src/lib/mcp/index.ts
var projectRef = "tbigtlfuittunagpyoxk";
var mcp_default = defineMcp({
  name: "getweb-task-mcp",
  title: "GetWeb Task",
  version: "0.1.0",
  instructions: "Tools for the GetWeb Task work-tracker app. Manage your own tasks and time sessions. Admins can also read team activity. Each user connects with their own account via OAuth; all reads and writes respect app permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_tasks_default, create_task_default, complete_task_default, start_timer_default, stop_timer_default, team_activity_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
