// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-tasks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  const supabaseUrl = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const supabaseKey = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") : process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_tasks_default = defineTool({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List tasks belonging to the signed-in user. Optional filters by date (YYYY-MM-DD) or status.",
  inputSchema: {
    date: z.string().optional().describe("Filter by date (YYYY-MM-DD)"),
    status: z.enum(["Not Started", "In Progress", "Finished"]).optional(),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const { date, status, limit } = input;
      console.log(`[Tool] list_my_tasks invoked with input:`, JSON.stringify(input));
      if (!ctx.isAuthenticated()) {
        console.warn(`[Tool] list_my_tasks authentication failed.`);
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const userId = ctx.getUserId();
      console.log(`[Tool] list_my_tasks authenticated user ID:`, userId);
      let q = sb(ctx).from("tasks").select("*").eq("user_id", userId).order("created_at", { ascending: false }).limit(limit ?? 50);
      if (date) q = q.eq("date", date);
      if (status) q = q.eq("status", status);
      const { data, error } = await q;
      if (error) {
        console.error(`[Tool] list_my_tasks Supabase query error:`, error);
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      console.log(`[Tool] list_my_tasks execution successful.`);
      return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { tasks: data } };
    } catch (err) {
      console.error(`[Tool] list_my_tasks unhandled exception:`, err);
      return {
        isError: true,
        content: [{ type: "text", text: err instanceof Error ? err.message : String(err) }]
      };
    }
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  const supabaseUrl = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const supabaseKey = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") : process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient2(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a task for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1),
    description: z2.string().optional(),
    category: z2.string().optional().describe("Task category e.g. Development, Design, Video, Ads"),
    date: z2.string().describe("Date in YYYY-MM-DD"),
    target_minutes: z2.number().int().positive().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      console.log(`[Tool] create_task invoked with input:`, JSON.stringify(input));
      if (!ctx.isAuthenticated()) {
        console.warn(`[Tool] create_task authentication failed.`);
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const userId = ctx.getUserId();
      console.log(`[Tool] create_task authenticated user ID:`, userId);
      const { data, error } = await sb2(ctx).from("tasks").insert({
        user_id: userId,
        title: input.title,
        description: input.description ?? null,
        category: input.category ?? "Development",
        date: input.date,
        target_minutes: input.target_minutes ?? null,
        status: "Not Started"
      }).select().single();
      if (error) {
        console.error(`[Tool] create_task Supabase query error:`, error);
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      console.log(`[Tool] create_task execution successful.`);
      return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { task: data } };
    } catch (err) {
      console.error(`[Tool] create_task unhandled exception:`, err);
      return {
        isError: true,
        content: [{ type: "text", text: err instanceof Error ? err.message : String(err) }]
      };
    }
  }
});

// src/lib/mcp/tools/complete-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  const supabaseUrl = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const supabaseKey = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") : process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient3(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as Finished, stop any open timer, and optionally attach completion notes and a project link.",
  inputSchema: {
    task_id: z3.string().uuid(),
    completion_notes: z3.string().optional(),
    project_link: z3.string().url().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const { task_id, completion_notes, project_link } = input;
      console.log(`[Tool] complete_task invoked with input:`, JSON.stringify(input));
      if (!ctx.isAuthenticated()) {
        console.warn(`[Tool] complete_task authentication failed.`);
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const userId = ctx.getUserId();
      console.log(`[Tool] complete_task authenticated user ID:`, userId);
      const client = sb3(ctx);
      await client.from("time_sessions").update({ end_time: (/* @__PURE__ */ new Date()).toISOString() }).eq("task_id", task_id).is("end_time", null);
      const updates = { status: "Finished" };
      if (completion_notes) updates.completion_notes = completion_notes;
      if (project_link) updates.project_link = project_link;
      const { data, error } = await client.from("tasks").update(updates).eq("id", task_id).eq("user_id", userId).select().single();
      if (error) {
        console.error(`[Tool] complete_task Supabase query error:`, error);
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      console.log(`[Tool] complete_task execution successful.`);
      return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { task: data } };
    } catch (err) {
      console.error(`[Tool] complete_task unhandled exception:`, err);
      return {
        isError: true,
        content: [{ type: "text", text: err instanceof Error ? err.message : String(err) }]
      };
    }
  }
});

// src/lib/mcp/tools/start-timer.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  const supabaseUrl = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const supabaseKey = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") : process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient4(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var start_timer_default = defineTool4({
  name: "start_timer",
  title: "Start timer",
  description: "Start a time session on one of the signed-in user's tasks and set it to In Progress.",
  inputSchema: { task_id: z4.string().uuid() },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const { task_id } = input;
      console.log(`[Tool] start_timer invoked with input:`, JSON.stringify(input));
      if (!ctx.isAuthenticated()) {
        console.warn(`[Tool] start_timer authentication failed.`);
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const userId = ctx.getUserId();
      console.log(`[Tool] start_timer authenticated user ID:`, userId);
      const client = sb4(ctx);
      const { data, error } = await client.from("time_sessions").insert({ task_id, start_time: (/* @__PURE__ */ new Date()).toISOString(), created_by: userId }).select().single();
      if (error) {
        console.error(`[Tool] start_timer Supabase query error:`, error);
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      await client.from("tasks").update({ status: "In Progress" }).eq("id", task_id).eq("user_id", userId);
      console.log(`[Tool] start_timer execution successful.`);
      return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { session: data } };
    } catch (err) {
      console.error(`[Tool] start_timer unhandled exception:`, err);
      return {
        isError: true,
        content: [{ type: "text", text: err instanceof Error ? err.message : String(err) }]
      };
    }
  }
});

// src/lib/mcp/tools/stop-timer.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb5(ctx) {
  const supabaseUrl = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const supabaseKey = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") : process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient5(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var stop_timer_default = defineTool5({
  name: "stop_timer",
  title: "Stop timer",
  description: "Stop the currently open time session on the signed-in user's task.",
  inputSchema: { task_id: z5.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      const { task_id } = input;
      console.log(`[Tool] stop_timer invoked with input:`, JSON.stringify(input));
      if (!ctx.isAuthenticated()) {
        console.warn(`[Tool] stop_timer authentication failed.`);
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const userId = ctx.getUserId();
      console.log(`[Tool] stop_timer authenticated user ID:`, userId);
      const { data, error } = await sb5(ctx).from("time_sessions").update({ end_time: (/* @__PURE__ */ new Date()).toISOString() }).eq("task_id", task_id).is("end_time", null).select();
      if (error) {
        console.error(`[Tool] stop_timer Supabase query error:`, error);
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      console.log(`[Tool] stop_timer execution successful.`);
      return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { sessions: data } };
    } catch (err) {
      console.error(`[Tool] stop_timer unhandled exception:`, err);
      return {
        isError: true,
        content: [{ type: "text", text: err instanceof Error ? err.message : String(err) }]
      };
    }
  }
});

// src/lib/mcp/tools/team-activity.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb6(ctx) {
  const supabaseUrl = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_URL") : process.env.SUPABASE_URL;
  const supabaseKey = typeof Deno !== "undefined" ? Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") : process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient6(supabaseUrl, supabaseKey, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var team_activity_default = defineTool6({
  name: "team_activity",
  title: "Team activity snapshot",
  description: "Get the current team activity snapshot (admin only). Returns each member's active task and today's todo/progress/completed lists.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    try {
      console.log(`[Tool] team_activity invoked with input:`, JSON.stringify(input));
      if (!ctx.isAuthenticated()) {
        console.warn(`[Tool] team_activity authentication failed.`);
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const userId = ctx.getUserId();
      console.log(`[Tool] team_activity authenticated user ID:`, userId);
      const { data, error } = await sb6(ctx).rpc("get_team_activity");
      if (error) {
        console.error(`[Tool] team_activity Supabase query error:`, error);
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      console.log(`[Tool] team_activity execution successful.`);
      return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { activity: data } };
    } catch (err) {
      console.error(`[Tool] team_activity unhandled exception:`, err);
      return {
        isError: true,
        content: [{ type: "text", text: err instanceof Error ? err.message : String(err) }]
      };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "tbigtlfuittunagpyoxk";
var mcp_default = defineMcp({
  name: "getweb-task-mcp",
  title: "GetWeb Task",
  version: "0.1.0",
  instructions: "Tools for the GetWeb Task work-tracker app. Manage your own tasks and time sessions. Admins can also read team activity. Each user connects with their own account via OAuth; all reads and writes respect app permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_tasks_default, create_task_default, complete_task_default, start_timer_default, stop_timer_default, team_activity_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
